[MISC] Adding references to Apache ZooKeeper project
canonical/zookeeper-k8s-operator pull request #109
Opened 2024-10-03 20:21 UTC by deusebio

2024-10-16 21:23 UTC, grobbie approved these changes
Thanks

2024-10-24 10:20 UTC, grobbie approved these changes

2024-11-19 22:54 UTC, marcoppenheimer approved these changes

2024-11-21 09:02 UTC, grobbie requested changes

2024-11-21 09:02 UTC, grobbie commented on metadata.yaml
> +display-name: Apache Zookeeper - K8s
Should be **Charmed** Apache ZooKeeper

2024-11-21 19:53 UTC, izmalk approved these changes

2024-11-27 09:03 UTC, grobbie approved these changes

2024-11-27 22:34 UTC, merged