[DPE-3023] Add badges to README.md
canonical/zookeeper-k8s-operator pull request #57
Opened 2023-11-24 12:13 UTC by deusebio

2023-11-30 08:27 UTC, zmraul requested changes

2023-11-30 08:27 UTC, zmraul commented on README.md
> +[![CharmHub Badge](https://charmhub.io/zookeeper-k8s/badge.svg)](https://charmhub.io/zookeeper)
```suggestion
[![CharmHub Badge](https://charmhub.io/zookeeper-k8s/badge.svg)](https://charmhub.io/zookeeper-k8s)
```

2023-12-01 11:35 UTC, delgod approved these changes

2023-12-01 15:05 UTC, zmraul approved these changes

2023-12-01 15:28 UTC, merged